.TH qwavjoin 1 "february 2001" "quelcom 0.4.0" "quelcom man pages"

.SH NAME
qwavjoin \- join wav files

.SH SYNOPSIS
.na
.B qwavjoin
.RI [ option ]...\  file1\ file2 ...
.ad

.SH DESCRIPTION 
.LP
.B qwavjoin
reads a list of wav files and joins them in one wav file in the specified order. the files must have the same parameters (i.e. sampling rate, bytes per sample, ...) in order that the joining can be done.

.SH OPTIONS
.TP
.BR \-h ,\  \-\-help
show a brief help and exit.
.TP
\fB\-o\fR <\fIoutfile\fR>, \fB\-\-output\fR=<\fIoutfile\fR>
\fIoutfile\fR is the name of the file where all the samples will be copied. if this option is not used, the samples from the second to the last file of the list will be appended to \fIfile1\fR.
.TP
.BR \-v ,\  \-\-verbose
show which operations are done.
.TP
.BR \-V ,\  \-\-version
show version and exit.

.SH BUGS
.LP
tests has been done only with 44100 Hz 16 bit stereo files, though it may work with mono/stereo 8/16 bits files.

.SH AUTHOR
.LP
dmanye@etse.urv.es
.br
http://www.etse.urv.es/~dmanye/quelcom/quelcom.html

.SH SEE ALSO
.BR qwavinfo (1),
.BR qwavcut (1),
.BR qwavsilence (1),
.BR qwavfade (1),
.BR qwavheaderdump (1)
.br
.BR qmp3info (1),
.BR qmp3join (1),
.BR qmp3cut (1),
.BR qmp3check (1),
.BR qmp3report (1)
